name: Test and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium

    - name: Run tests
      run: npm test
      
    - name: Deploy to GitHub Pages
      if: success() # Solo se ejecuta si los tests han pasado
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: . # Aquí seleccionamos la raíz del repo, donde está el index.html
        force_orphan: true  # Crea la rama gh-pages si no existe, sin historia anterior

    - name: Display success message
      if: success()
      run: echo "Tests passed and deployed successfully to GitHub Pages!"
